function C = transfinitemapping(c,xi,eta,i,j)

bottom = (c(i,j)  +c(i+1,j)  )/2+(c(i+1,j)  -c(i,j)  )/2*xi;
top    = (c(i,j+1)+c(i+1,j+1))/2+(c(i+1,j+1)-c(i,j+1))/2*xi;
left   = (c(i,j)  +c(i,j+1)  )/2+(c(i,j+1)  -c(i,j)  )/2*eta;
right  = (c(i+1,j)+c(i+1,j+1))/2+(c(i+1,j+1)-c(i+1,j))/2*eta;

C = bottom*(1-eta)/2+...
    top*(1+eta)/2+...
    (1-xi)/2*left+...
    (1+xi)/2*right-...
    ( c(i,j)/4*(1-xi)*(1-eta)+...
      c(i+1,j)/4*(1+xi)*(1-eta)+...
      c(i,j+1)/4*(1-xi)*(1+eta)+...
      c(i+1,j+1)/4*(1+xi)*(1+eta) );
